-- MySQL Script generated by MySQL Workbench
-- Mon 06 May 2024 09:13:49 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `UUID` CHAR(36) BINARY NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UUID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `users_UUID` CHAR(36) BINARY NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `enrollmentStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`users_UUID`),
  CONSTRAINT `fk_students_users1`
    FOREIGN KEY (`users_UUID`)
    REFERENCES `mydb`.`users` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_students_users1_idx` ON `mydb`.`students` (`users_UUID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admins` (
  `users_UUID` CHAR(36) BINARY NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_UUID`),
  CONSTRAINT `fk_admins_users1`
    FOREIGN KEY (`users_UUID`)
    REFERENCES `mydb`.`users` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admins_users1_idx` ON `mydb`.`admins` (`users_UUID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`professors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`professors` (
  `users_UUID` CHAR(36) BINARY NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_UUID`),
  CONSTRAINT `fk_professors_users1`
    FOREIGN KEY (`users_UUID`)
    REFERENCES `mydb`.`users` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_professors_users1_idx` ON `mydb`.`professors` (`users_UUID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `courseID` VARCHAR(45) NOT NULL,
  `professors_users_UUID` CHAR(36) BINARY NOT NULL,
  `students_users_UUID` CHAR(36) BINARY NOT NULL,
  `meetingTime` VARCHAR(45) NULL,
  `meetingDays` VARCHAR(45) NULL,
  PRIMARY KEY (`courseID`, `professors_users_UUID`),
  CONSTRAINT `fk_courses_professors1`
    FOREIGN KEY (`professors_users_UUID`)
    REFERENCES `mydb`.`professors` (`users_UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_students1`
    FOREIGN KEY (`students_users_UUID`)
    REFERENCES `mydb`.`students` (`users_UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_courses_professors1_idx` ON `mydb`.`courses` (`professors_users_UUID` ASC) VISIBLE;

CREATE INDEX `fk_courses_students1_idx` ON `mydb`.`courses` (`students_users_UUID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `roleID` VARCHAR(45) NOT NULL,
  `users_UUID` CHAR(36) BINARY NOT NULL,
  PRIMARY KEY (`roleID`),
  CONSTRAINT `fk_roles_users1`
    FOREIGN KEY (`users_UUID`)
    REFERENCES `mydb`.`users` (`UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_roles_users1_idx` ON `mydb`.`roles` (`users_UUID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`permissions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `permissionID` INT NOT NULL,
  `permissions` VARCHAR(45) NULL,
  `roles_roleID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permissionID`, `roles_roleID`),
  CONSTRAINT `fk_permissions_roles1`
    FOREIGN KEY (`roles_roleID`)
    REFERENCES `mydb`.`roles` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_permissions_roles1_idx` ON `mydb`.`permissions` (`roles_roleID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`grades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grades` (
  `students_users_UUID` CHAR(36) BINARY NOT NULL,
  `courses_courseID` VARCHAR(45) NOT NULL,
  `courses_professors_users_UUID` CHAR(36) BINARY NOT NULL,
  PRIMARY KEY (`students_users_UUID`),
  CONSTRAINT `fk_grades_students1`
    FOREIGN KEY (`students_users_UUID`)
    REFERENCES `mydb`.`students` (`users_UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_courses1`
    FOREIGN KEY (`courses_courseID` , `courses_professors_users_UUID`)
    REFERENCES `mydb`.`courses` (`courseID` , `professors_users_UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_grades_courses1_idx` ON `mydb`.`grades` (`courses_courseID` ASC, `courses_professors_users_UUID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`assignments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`assignments` (
  `grades_students_users_UUID` CHAR(36) BINARY NOT NULL,
  `percentageGrade` DOUBLE(5,2) NULL,
  PRIMARY KEY (`grades_students_users_UUID`),
  CONSTRAINT `fk_assignments_grades1`
    FOREIGN KEY (`grades_students_users_UUID`)
    REFERENCES `mydb`.`grades` (`students_users_UUID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
